### ISSUE TITLE
@delon/abc

### ISSUE THREAD

**Issue by mgechev** [angular/ngcc-validation#110]
```
ERROR in There is no appropriate source code format in '/Users/mgechev/Projects/ngcc-validation/delonabc-ngcc/node_modules/date-fns/add_seconds' entry-point.
```

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular/issues/32097

**Comment by mgechev** [comment]
@petebacondarwin looks like this is still failing:

```
ERROR in The target entry-point "@delon/abc" has missing dependencies:
 - date-fns/add_seconds
```

Although it looks like a problem with the package itself? I checked `date-fns` and didn't find `add_seconds` there.

**Comment by petebacondarwin** [comment]
Despite not declaring them as a dependency, this library does try to import the `date-fns` library. See https://github.com/ng-alain/delon/blob/master/packages/abc/count-down/count-down.component.ts#L2-L3
