### ISSUE TITLE
Transform to workspaces

### ISSUE THREAD

**Issue by stalniy** [angular/ngcc-validation#1128]
It's extremely hard to add own library into the project because first you need to install 200 000+ dependencies! And this is just the beginning. When everybody will add own library it will be a lot more and it will be very hard (and long) to add and test own library.

So, I **propose to convert this project to monorepo using yarn workspaces**. This way each library dependencies will be in its own folder and in order to test 1 library I don't need to install thousands of dependencies which I even don't plan to use in my tests.

**Comment by gkalpak** [comment]
Thx for opening this issue, @stalniy. Unfortunately, I don't think moving this project to yarn workspaces is a viable option at this moment. AFAIK, the CLI does not currently support yarn workspaces and ngcc itself doesn't play well with them either.

So, I am afraid we will have to deal with the top-level deps for now 😞

##
BTW, this repo is not supposed to include all Angular libs :grin:
We try to include the most popular ones (and we might accept contributions for less popular ones), we don't expect the list of packages to grow significantly going forward.

**Comment by stalniy** [comment]
I see. Thanks for the response!
