### ISSUE TITLE
@swimlane/ngx-dnd

### ISSUE THREAD

**Issue by mgechev** [angular/ngcc-validation#124]
```
ERROR in Cannot combine @Input decorators with query decorators
```

**Comment by earshinov** [comment]
For anyone interested. @swimlane/ngx-dnd issue to track:

- https://github.com/swimlane/ngx-dnd/issues/150
- https://github.com/swimlane/ngx-dnd/pull/151

**Comment by mgechev** [comment]
This is now passing.
