### ISSUE TITLE
ci: Renovate auto-closes PRs for dependencies targeting GitHub commits

### ISSUE THREAD

**Issue by gkalpak** [angular/ngcc-validation#1529]
Capturing the issue here for reference:

Recently, Renovate started not being able to update dependencies targeting GitHub commits (not npm versions) - i.e. [Angular CLI], [Angular framework], [Angular Components] and [Angular flex-layout]. More specifically, Renovate will create the PRs correctly, but then close them (for no apparent reason) a few minutes later.

You can see a list of autoclosed PRs [here][1].
Not sure if it is related, but for a few days before 2020-07-08, the PRs were autoclosed with a [message][2] about failing to update `yarn.lock`

For example, PR #1528 was created and then auto-closed by Renovate 10 mins later. You can see the logs for creating it in [log-202799678.][3] (you can filter by `Branch: renovate/angular-components`, but other lines might be relevant as well) and the logs for closing it in [log-202800102][4]. I couldn't figure out why this is happening based on the logs. 

I also uploaded the logs for anyone that doesn't have access to the dashboard: 
- [renovate-log-202799678.txt](https://github.com/angular/ngcc-validation/files/4918660/renovate-log-202799678.txt)
- [renovate-log-202800102.txt](https://github.com/angular/ngcc-validation/files/4918661/renovate-log-202800102.txt)

And as gists:
- [renovate-log-202799678.txt](https://gist.github.com/gkalpak/5fe494117431749995d7bede1641729b)
- [renovate-log-202800102.txt](https://gist.github.com/gkalpak/7aec0c88d87edc69bf12c3c7ad0b1443)

[Angular CLI]: https://github.com/angular/ngcc-validation/blob/94fd511b779654aabef920937cdf956c87222ca7/package.json#L279
[Angular Components]: https://github.com/angular/ngcc-validation/blob/94fd511b779654aabef920937cdf956c87222ca7/package.json#L32
[Angular flex-layout]: https://github.com/angular/ngcc-validation/blob/94fd511b779654aabef920937cdf956c87222ca7/package.json#L28
[Angular framework]: https://github.com/angular/ngcc-validation/blob/94fd511b779654aabef920937cdf956c87222ca7/package.json#L25

[1]: https://github.com/angular/ngcc-validation/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate+created%3A%3E2020-07-08T11%3A00+autoclosed
[2]: https://github.com/angular/ngcc-validation/pull/1474#issuecomment-655401889
[3]: https://app.renovatebot.com/dashboard#github/angular/ngcc-validation/202799678
[4]: https://app.renovatebot.com/dashboard#github/angular/ngcc-validation/202800102

**Comment by alan-agius4** [comment]
https://github.com/renovatebot/renovate/issues/6750

**Comment by gkalpak** [comment]
The issue has been fixed with renovatebot/renovate#6799. See, for example, #1581 and #1582 :tada:
