### ISSUE TITLE
[@momentum-ui/angular] Got: 'ERROR in Cannot read property 'visit' of undefined'

### ISSUE THREAD

**Issue by Teamop** [angular/ngcc-validation#374]
I just played with this `@momentum-ui/angular`, seems no matter `ng build` or `ng serve`, all got the error: `ERROR in Cannot read property 'visit' of undefined`.
1. Setup
   - create new project
   - install `@momentum-ui/angular`
   - also install `lodash-es` for peer dependency
2. Import some modules from `@momentum-ui/angular`, like 
   - `import { BadgeModule } from '@momentum-ui/angular';`
   - `imports: [
    BadgeModule.forRoot(),
    BrowserModule
  ],`

Then got the error when `ng build` or `ng serve` - `ERROR in Cannot read property 'visit' of undefined`.
![image](https://user-images.githubusercontent.com/8519685/66451796-8c353c00-ea90-11e9-823f-e1fff61a5b54.png)

**Comment by IgorMinar** [comment]
Is this an ngtsc error (does it show up when you do `ng build`?) or an actual runtime error?

**Comment by Teamop** [comment]
yes, same error when `ng build`

**Comment by gkalpak** [comment]
FWIW, this is failing on [this line][1]:

```ts
@Component({
  selector: 'md-date-picker-day',
  ...
  host: {
    ...
    '[attr.ariaLabel]': '',
```

It seems that the empty string causes [convertPropertyBinding()][2] to be called with `expressionWithoutBuiltins` being `undefined`, which throws when trying to [visit it as AST][3].

##
I am still investigating what is the best way to address this (e.g. fix the error or throw earlier with a more informative message). From a quick look I believe [parsePropertyBinding()][4] should throw when called with an empty string as `expression` (or maybe treat it the same as `'""'`, which was likely the intention).

Anyway, I just wanted to give a quick update.

[1]: https://github.com/momentum-design/momentum-ui/blob/bdd66e8b8/angular/src/lib/date-picker/date-picker-day.component.ts#L27
[2]: https://github.com/angular/angular/blob/c88305d2e/packages/compiler/src/compiler_util/expression_converter.ts#L158-L161
[3]: https://github.com/angular/angular/blob/c88305d2e/packages/compiler/src/compiler_util/expression_converter.ts#L168
[4]: https://github.com/angular/angular/blob/c88305d2e/packages/compiler/src/template_parser/binding_parser.ts#L183-L186

**Comment by gkalpak** [comment]
(Potentially related to angular/angular#30938.)

**Comment by gkalpak** [comment]
I tried with the latest versions of Angular and `@moment-ui/angular` and this doesn't seem to be a problem any more. (I got a different error, but that doesn't seem to be related to ngcc :grin:)

If you are still running into ngcc compilation failures, please open a new issue on the [angular/angular](https://github.com/angular/angular/issues) repo.
