### ISSUE TITLE
Why build only NGXS (store, hmr) without router, logger, etc plugin?

### ISSUE THREAD

**Issue by splincode** [angular/ngcc-validation#688]
![image](https://user-images.githubusercontent.com/12021443/70836260-b7316880-1e10-11ea-807f-ca94cdcddea7.png)

**Comment by splincode** [comment]
@mgechev Why `import "@ngxs/router-plugin"`?


![image](https://user-images.githubusercontent.com/12021443/70836510-64a47c00-1e11-11ea-82ef-be8c2b745136.png)

Instead 

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { NgxsRouterPluginModule } from '@ngxs/router-plugin';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgxsRouterPluginModule.forRoot() // <--- correct behavior
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I have build error with Angular 9.rc-6

![image](https://user-images.githubusercontent.com/12021443/70836609-bb11ba80-1e11-11ea-88c8-46b27a0924ff.png)

**Comment by splincode** [comment]
https://github.com/angular/angular/issues/34191

**Comment by mgechev** [comment]
Some of the projects are still automatically generated. An import of the library is often good enough to trigger ngcc and verify it works, but as you noticed, not always. Would you open a PR?
